name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: return the num_squared
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: fetch num squared
        id: get-square
        uses: ./
        with:
          num: 11
      - name: print the square
        run: echo "${{ steps.get_square.outputs.num_squared }}"
